name: amar_karigor
version: 1.0.0+1
publish_to: none
description: Ami Karigor.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.0.0
  http: ^0.13.0
  salomon_bottom_bar: ^3.1.0
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  shared_preferences: ^2.0.0
  shimmer: ^2.0.0
  carousel_slider: ^4.0.0
  syncfusion_flutter_sliders: ^19.4.40
  table_calendar: ^3.0.3
  flutter_svg: ^0.22.0
  url_launcher: ^6.0.20
  webview_flutter: ^2.0.13
  
 
  flutter: 
    sdk: flutter
  firebase_database: ^9.0.12
 

dev_dependencies: 
  flutter_test: 
    sdk: flutter  

flutter: 
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/


